name: Turnos Local
values:
  - key: baseUrl
    value: 'http://localhost:8080'
    enabled: true
    type: default
  - key: username
    value: admin
    enabled: true
    type: default
  - key: password
    value: admin123
    enabled: true
    type: default
  - key: turnoId
    value: '1'
    enabled: true
    type: default
