spring.datasource.url=jdbc:postgresql://dpg-d8a16fjbc2fs73fln1mg-a/turnos_db_vcpf?sslmode=disable&connectTimeout=10&socketTimeout=60
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.hikari.connection-timeout=15000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

google.client-id=205021739328-dl841da3vg0s62mgi90cv355ovh9emvh.apps.googleusercontent.com
spring.security.user.name=${ADMIN_USERNAME:admin}
spring.security.user.password=${ADMIN_PASSWORD:admin123}

server.port=${PORT:8080}